### ISSUE TITLE
Foobar pcb/gerber files

### ISSUE THREAD

**Issue by FSund** [di0ib/Misc#1]
Hi, I love your posts on lots of different keyboards, and especially like that you share both gerber files and firmwares. But I can't seem to find the gerber files for the foobar keyboard mentioned in this post: http://www.40percent.club/2017/09/foobar-10.html?m=1

Do you mind sharing the files? One half of that would serve perfectly as a macropad for me, and it should even fit within the 100x100 mm specials.

**Comment by di0ib** [comment]
There are issues with this version. When a revised versions passes tests I will release it.

**Comment by di0ib** [comment]
Revised version has been release. https://github.com/di0ib/Misc/tree/master/foobar

**Comment by FSund** [comment]
Great work! I am definitely ordering a couple of those to use as numberpads.
